openapi: 3.0.3
info:
  title: HtAG Intelligence APIs
  version: 1.0.2
  description: |
    Domain-partitioned APIs for HtAG Intelligence. Initial domain: **Address**.
servers:
  - url: https://api.htagai.com/v1

tags:
  - name: Address
    description: "Address Intelligence domain: query address-level indicators (e.g., bushfire/flood flags, SEIFA, public housing)."
  - name: Marketing
    description: "Marketing Intelligence domain (reserved for future endpoints)."

x-tagGroups:
  - name: API Products
    tags:
      - Address
      - Marketing

paths:
  /address/insights:
    get:
      tags: [Address]
      operationId: getAddressInsights
      summary: Retrieve address data by key(s), legal parcel ID, or street locality
      description: |
        Returns address-level data for provided identifiers, with options to filter by mesh block category.

        **Exactly one** of the following query parameters must be supplied per request:
        - `address_keys`
        - `legal_parcel_id`
        - `street_loc_pid`
      x-htg-exactlyOne:
        - address_keys
        - legal_parcel_id
        - street_loc_pid
      parameters:
        - $ref: '#/components/parameters/AddressKeys'
        - $ref: '#/components/parameters/LegalParcelId'
        - $ref: '#/components/parameters/StreetLocPid'
        - $ref: '#/components/parameters/MbCategory2021'
      responses:
        '200':
          description: List of address-level records matching the query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressInsightsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'

components:
  parameters:
    AddressKeys:
      in: query
      name: address_keys
      description: |
        Up to 50 address key values.

        **Only one of `address_keys`, `legal_parcel_id`, or `street_loc_pid` can be provided in a single request.**
      required: false
      schema:
        type: array
        items:
          type: string
        maxItems: 50
      style: form
      explode: false
      example:
        - 100102HICKOXSTREETTRARALGONVIC3844
        - 100106GREYSTREETTRARALGONVIC3844

    LegalParcelId:
      in: query
      name: legal_parcel_id
      description: |
        One legal parcel ID value.

        **Only one of `address_keys`, `legal_parcel_id`, or `street_loc_pid` can be provided in a single request.**
      required: false
      schema:
        type: string
      example: "2\\TP574754"

    StreetLocPid:
      in: query
      name: street_loc_pid
      description: |
        Query all addresses by Street Locality PID (e.g., a street).

        **Only one of `address_keys`, `legal_parcel_id`, or `street_loc_pid` can be provided in a single request.**
      required: false
      schema:
        type: string
      example: VIC2572

    MbCategory2021:
      in: query
      name: mb_category_2021
      description: Mesh Block category (defaults to Any)
      required: false
      schema:
        type: array
        items:
          type: string
          enum:
            - Residential
            - Commercial
            - Parkland
            - Other
            - Primary Production
            - Education
            - Water
            - Industrial
            - Transport
            - Hospital/Medical
            - SHIPPING
            - MIGRATORY
            - OFFSHORE
            - NOUSUALRESIDENCE
            - ANTARCTICA
            - Outside Australia
      style: form
      explode: false
      example: [Residential, Commercial]

  responses:
    BadRequest:
      description: Invalid input or parameter constraints violated
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: object
                additionalProperties: true

  schemas:
    AddressInsightsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AddressRecord'
        total:
          type: integer
          description: Number of records returned

    AddressRecord:
      type: object
      properties:
        address_key:
          type: string
          example: 100102HICKOXSTREETTRARALGONVIC3844
        gnaf_property_pid:
          type: string
          nullable: true
          example: 52534163
        legal_parcel_id:
          type: string
          nullable: true
          example: 3\\PS408857
        mb_category:
          type: string
          example: Residential
        street_loc_pid:
          type: string
          example: VIC2572
        lat:
          type: number
          format: double
          example: -38.20867268
        lon:
          type: number
          format: double
          example: 146.53163935
        flood:
          type: boolean
          nullable: true
          description: Flood flagged for this property (true=Yes, false=No, null=unknown)
          example: false
        bushfire:
          type: boolean
          nullable: true
          description: Bushfire flagged for this property (true=Yes, false=No, null=unknown)
          example: true
        heritage:
          type: boolean
          nullable: true
          description: Heritage flagged for this property (true=Yes, false=No, null=unknown)
          example: null
        zoning:
          type: string
          nullable: true
          example: null
        IRSD:
          type: integer
          nullable: true
          example: 4
        IRSAD:
          type: integer
          nullable: true
          example: 4
        IER:
          type: integer
          nullable: true
          example: 4
        IEO:
          type: integer
          nullable: true
          example: 3
        public_housing:
          type: number
          format: float
          example: 0.45
